workflows:
  android_release:
    name: Android Release (Email APK)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Pre-build (create android project + get deps)
        script: |
          flutter create -t app . --org com.shakir --project-name shakir_drive --overwrite
          flutter pub get
      - name: Build APK (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - aalexx59@gmail.com
        notify:
          success: true
          failure: true
        attachments:
          - build/**/outputs/**/*.apk
