workflows:
  shakir_android:
    name: Shakir Android APK
    environment:
      flutter: 3.19.6
      vars:
        APP_NAME: "SHAKIR DRIVE"
    scripts:
      - name: Flutter clean & deps
        script: |
          flutter --version
          flutter clean
          flutter pub get
      - name: Build release APK
        script: |
          cd android
          ./gradlew clean
          cd ..
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - aaalexx59@gmail.com
        notify:
          success: true
          failure: true
