workflows:
  android_release:
    name: Android Release (Email APK)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Pre-build (get dependencies)
        script: |
          flutter pub get
      - name: Build APK (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - aalexx59@gmail.com
