workflows:
  shakir_android:
    name: Shakir Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        APP_PACKAGE: "com.shakirdriveapp"
        APP_NAME: "SHAKIR DRIVE"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true

    scripts:
      # 1) Nettoyer ce qui pourrait gêner
      - name: Clean repository
        script: |
          git clean -fdx

      # 2) Regénérer **Android** propre (embedding v2 + gradle wrapper)
      - name: Recreate fresh Android directory (embedding v2)
        script: |
          rm -rf android
          flutter --version
          flutter create . --platforms=android --org $APP_PACKAGE -a kotlin
          flutter pub get

      # 3) Ajuster le nom d’appli pour l’icône/launcher (facultatif)
      - name: Set Android app label
        script: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          sed -i.bak 's/android:label="[^"]*"/android:label="'"$APP_NAME"'"/' "$MANIFEST" || true
          echo "App label set to: $APP_NAME"

      # 4) Construire l’APK (release)
      - name: Build release APK (Flutter)
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - "aalexx59@gmail.com"   # <-- mets ton adresse ici
        notify:
          success: true
          failure: true
