workflows:
  shakir_android:
    name: Shakir Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK (release)
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - aalexx59@gmail.com
