workflows:
  android_release:
    name: Android Release (Email APK)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      # 1) Génère la structure Flutter (android/, ios/, etc.) sans écraser ton code existant
      - name: Create Flutter project structure if missing
        script: |
          flutter --version
          flutter create . || true
      # 2) Récupère les dépendances
      - name: Pre-build (get dependencies)
        script: |
          flutter pub get
      # 3) Build APK release
      - name: Build APK (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - aalexx59@gmail.com
