workflows:
  shakir_android:
    name: Shakir Android APK
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      vars:
        APP_ID: "com.shakirdriveapp"
        APP_LABEL: "SHAKIR DRIVE"
    scripts:
      - name: Préparer le projet Flutter/Android
        script: |
          flutter --version
          # Crée/actualise la structure Android moderne si besoin (embedding v2 + gradle wrapper)
          if [ ! -d "android" ] || [ ! -f "android/gradlew" ]; then
            flutter create . --platforms=android --org $APP_ID
          fi
          chmod +x android/gradlew || true

          # Forcer compileSdk/minSdk compatibles
          sed -i.bak 's/compileSdk *[0-9]\+/compileSdk 34/' android/app/build.gradle || true
          sed -i.bak 's/minSdkVersion *[0-9]\+/minSdkVersion 21/' android/app/build.gradle || true

          # Mettre le label de l'application
          MANIFEST=android/app/src/main/AndroidManifest.xml
          if grep -q 'android:label=' "$MANIFEST"; then
            sed -i.bak "s/android:label=\"[^\"]*\"/android:label=\"$APP_LABEL\"/" "$MANIFEST"
          else
            sed -i.bak "s/<application /<application android:label=\"$APP_LABEL\" /" "$MANIFEST"
          fi

      - name: Récupérer les paquets & générer l’icône
        script: |
          flutter pub get
          flutter pub run flutter_launcher_icons

      - name: Construire l’APK release
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          # ➜ Remplace par TON email
          - aalexx59@gmail.com
