workflows:
  shakir_android:
    name: Shakir Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.shakirdriveapp"
    scripts:
      - name: Flutter clean & deps
        script: |
          flutter --version
          flutter clean
          flutter pub get
      - name: Build release APK (Flutter)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - aalexx59@gmail.com   # <-- mets ton e-mail exact ici
        notify:
          success: true
          failure: true
