workflows:
  shakir_android:
    name: Shakir Android APK
    max_build_duration: 60
    environment:
      flutter: stable    # Codemagic installera la dernière stable de Flutter
      vars:
        APP_NAME: "SHAKIR DRIVE"
    scripts:
      - name: Flutter doctor (optionnel)
        script: |
          flutter --version
          flutter doctor -v
      - name: Get packages
        script: |
          flutter pub get
      - name: Build release APK (Flutter)
        script: |
          # Nettoyage léger (optionnel)
          flutter clean
          # Compile l'APK en mode release
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - aalexx59@gmail.com   # <- ton adresse e-mail
        notify:
          success: true
          failure: true
