workflows:
  shakir_android:
    name: Shakir Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Clean & get dependencies
        script: |
          flutter --version
          flutter clean
          flutter pub get

      - name: Recreate modern Android folder (Embedding v2)
        script: |
          # On supprime l'ancien dossier android (incomplet/v1)
          rm -rf android
          # On recrée la plateforme Android moderne (embedding v2 + gradlew)
          flutter create --platforms=android .

      - name: Set package id, app label and icon
        script: |
          python3 - <<'PY'
          import re, io, os

          # 1) applicationId dans android/app/build.gradle
          p = 'android/app/build.gradle'
          s = open(p, 'r', encoding='utf-8').read()
          s = re.sub(r'applicationId\s+"[^"]+"', 'applicationId "com.shakirdriveapp"', s)
          open(p, 'w', encoding='utf-8').write(s)

          # 2) label + icône dans AndroidManifest.xml
          p = 'android/app/src/main/AndroidManifest.xml'
          s = open(p, 'r', encoding='utf-8').read()
          s = re.sub(r'android:label="[^"]+"', 'android:label="SHAKIR DRIVE"', s)
          # On garde ic_launcher (les mipmaps par défaut existent)
          s = re.sub(r'android:icon="@mipmap/ic_launcher"', 'android:icon="@mipmap/ic_launcher"', s)
          open(p, 'w', encoding='utf-8').write(s)
          PY

      - name: Build release APK (Flutter)
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - VOTRE_EMAIL_ICI
        subject: "SHAKIR DRIVE - APK"
        body: "APK de SHAKIR DRIVE généré avec succès."
